trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        vmImage: 'Ubuntu-16.04'
      continueOnError: false
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'
        workingDirectory: 'Butter.Web'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'Butter.Web'
          Contents: |
            dist/*.js
            style/*.css
            index.html
          TargetFolder: 'Web'
          CleanTargetFolder: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'Web'
          artifact: 'web'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          projects: 'Butter.Backend/Butter.Backend.csproj'
          publishWebProjects: false  
          arguments: '--output $(Build.ArtifactStagingDirectory)/Backend'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'deployment'
          artifact: 'deployment'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/Backend'
          artifact: 'backend'
- stage: PublishAzure
  jobs:
  - deployment: DeployArm
    pool:
        vmImage: 'Ubuntu-16.04'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'deployment'
              targetPath: '$(Pipeline.Workspace)'
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: 'MVP Sponsorship(58ac7037-efcc-4fb6-800d-da6ca2ee6aed)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'butter-prod-euw-rg'
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmParametersFile: '$(Pipeline.Workspace)/deployment/butter.parameters.json'
              csmFile: '$(Pipeline.Workspace)/deployment/butter.json'
              deploymentMode: 'Incremental'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'MVP Sponsorship(58ac7037-efcc-4fb6-800d-da6ca2ee6aed)'
              appType: 'webApp'
              WebAppName: 'butter-prod-euw-functionapp'
              packageForLinux: '$(Pipeline.Workspace)/Backend/Butter.Backend'